name = "CIFDictTools"
uuid = "eef223a7-a1bb-432c-8842-89606d067be4"
version = "0.1.0"
authors = ["James.Hester <jxh@ansto.gov.au>"]

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CrystalInfoFramework = "6007d9b0-c6b2-11e8-0510-1d10e825f3f1"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Lerche = "d42ef402-04e6-4356-9f73-091573ea58dc"
